options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT: 'snapshottask'
  _LABELS: 'env=dev,owner=boss'
  _RETENTION: '7'
  _ACTIVITY: 'nightly'
  _BACKUP_TYPE: 'incremental'
  _STORAGE_LOCATION: ''
  _DRYRUN_FLAG: ''   # set '' in trigger to run for real

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e

        echo "==> Installing jq..."
        apt-get update -y
        apt-get install -y jq

        echo "==> Making snapshot script executable..."
        chmod +x snapshot_gcp.sh

        echo "==> Running snapshot script..."
        ./snapshot_gcp.sh \
          --servers-file servers.txt \
          --project "${_PROJECT}" \
          --labels "${_LABELS}" \
          --retention-days ${_RETENTION} \
          --activity "${_ACTIVITY}" \
          --backup-type ${_BACKUP_TYPE} \
          --storage-location "${_STORAGE_LOCATION}" \
          ${_DRYRUN_FLAG}

timeout: '1200s'
